name: .NET Desktop Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2
        if: success()

      - name: Restore NuGet packages
        run: nuget restore "**/*.sln"
        if: success()

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        if: success()

      - name: Build Solution
        run: msbuild "**/*.sln" /p:Configuration=Release /p:Platform="Any CPU"
        if: success()

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: Rubeus/bin/Release/
        if: success()
